/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DonationContract } from "./DonationContract";
export * as factories from "./factories";
export { DonationContract__factory } from "./factories/DonationContract__factory";
